make sdk:
    source '/workspace/gcloud/google-cloud-sdk/path.bash.inc'
    source '/workspace/gcloud/google-cloud-sdk/completion.bash.inc'
    gcloud auth login
    export GOOGLE_APPLICATION_CREDENTIALS=apikey.json
    
